# Configuration des logs pour l'application ECF DAO

# Niveau global
.level=ALL

# Niveaux par package
main.com.julio.dao.level=FINE
main.com.julio.model.level=INFO
main.com.julio.service.level=INFO

# Handlers
handlers=java.util.logging.FileHandler, java.util.logging.ConsoleHandler

# FileHandler
java.util.logging.FileHandler.pattern=logs/ecf_dao_%u.log
java.util.logging.FileHandler.limit=5242880
java.util.logging.FileHandler.count=10
java.util.logging.FileHandler.level=ALL
java.util.logging.FileHandler.formatter=main.com.julio.util.LoggerUtil$CustomFormatter

# ConsoleHandler
java.util.logging.ConsoleHandler.level=INFO
java.util.logging.ConsoleHandler.formatter=main.com.julio.util.LoggerUtil$CustomFormatter
